name: torch-gpu
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - pip
  - python=3.9
  - matplotlib
  - simpleitk
  - pytorch-cuda=11.8
  - torchvision
  - torchmetrics
  - tqdm
  - wandb
  - pip:
    - pandas
    - torch-summary